// Generated by jextract

package org.cryptobiotic.gmp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct {
 *     int _mp_alloc;
 *     int _mp_size;
 *     mp_limb_t* _mp_d;
 * };
 * }
 */
public class __mpz_struct {

    public static MemoryLayout $LAYOUT() {
        return constants$0.const$0;
    }
    public static VarHandle _mp_alloc$VH() {
        return constants$0.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int _mp_alloc;
     * }
     */
    public static int _mp_alloc$get(MemorySegment seg) {
        return (int)constants$0.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int _mp_alloc;
     * }
     */
    public static void _mp_alloc$set(MemorySegment seg, int x) {
        constants$0.const$1.set(seg, x);
    }
    public static int _mp_alloc$get(MemorySegment seg, long index) {
        return (int)constants$0.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void _mp_alloc$set(MemorySegment seg, long index, int x) {
        constants$0.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle _mp_size$VH() {
        return constants$0.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int _mp_size;
     * }
     */
    public static int _mp_size$get(MemorySegment seg) {
        return (int)constants$0.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int _mp_size;
     * }
     */
    public static void _mp_size$set(MemorySegment seg, int x) {
        constants$0.const$2.set(seg, x);
    }
    public static int _mp_size$get(MemorySegment seg, long index) {
        return (int)constants$0.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void _mp_size$set(MemorySegment seg, long index, int x) {
        constants$0.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle _mp_d$VH() {
        return constants$0.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * mp_limb_t* _mp_d;
     * }
     */
    public static MemorySegment _mp_d$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$0.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * mp_limb_t* _mp_d;
     * }
     */
    public static void _mp_d$set(MemorySegment seg, MemorySegment x) {
        constants$0.const$3.set(seg, x);
    }
    public static MemorySegment _mp_d$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$0.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void _mp_d$set(MemorySegment seg, long index, MemorySegment x) {
        constants$0.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


